title: Discussion - <discussion topic here>
labels:
  - help wanted
body:
  - type: markdown
    attributes:
      value: |
        Use this to start a discussion between the members of this repo on some topic.
        Use the questions category if you just want an answer to a question.
  - type: textarea
    attributes:
      label: Starting a Discussion
      placeholder: I would like to discuss...
      value: I would like to discuss
    validations:
      required: true
