body:
  - type: markdown
    attributes:
      value: "Use this to Start a discussion between the members of this repo on some topic. Use the Q&A category if you just want a question and answer."
  - type: textarea
    attributes:
      label: discussion
      placeholder: I would like to discuss...
      value: Discussion topic
    validations:
      required: true
